- name: "DEBUG:: provisioning resource group {{ res_grp }}"
  debug:
    msg: "The current server obj is {{ res_grp }} "

- name: "Including credentials of current resource {{ res_grp['resource_group_name'] }} "
  include_vars: "../vars/{{ res_grp['assoc_creds'] }}.yml"
  no_log: true 

- name: "Parsing topology output file "
  output_parser:
    output_file: "{{ topo_output_file }}"
  register: topo_output

- name: "Deprovisioning resource definitions of current group"
  include: deprovision_res_defs.yml res_def={{ res_item.0 }} tp_out={{ res_item.1 }} res_grp_name={{ res_item.2 }}
  when: res_item.0['res_type'] == "aws_ec2"
  with_nested:
    - "{{ res_grp['res_defs'] }}"
    - "{{ topo_output['output']['content']['aws_ec2_res'] }}"
    - ["{{ res_grp['resource_group_name']  }}"]
  loop_control:
    loop_var: res_item

- name: "Deprovisioning s3 resource def of current group"
  include: deprovision_s3_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  when: res_item.0['res_type'] == "aws_s3"
  with_nested:
    - "{{ res_grp['res_defs'] }}"
    - ["{{ res_grp['resource_group_name']  }}"]
  loop_control:
    loop_var: res_item

