- name: "Debug:: checking heat parameters "
  debug:
    msg: "{{ res_grp_vars | selectattr('resource_group_name', 'equalto', res_grp_name ) | first }}"

- name: "Set Heat parameters for template"
  set_fact:
    heat_params : "{{ res_grp_vars | selectattr('resource_group_name', 'equalto', res_grp_name ) | first }}"

- name: "Set Heat parameters for template"
  set_fact:
    heat_params : "{{ heat_params['heat_params'] }}"

- name: "Provision os_heat stack"
  os_hot_stack:
    stack_name: "{{ res_def['res_name']  }}"
    template: "{{ res_def['template_path']  }}"
    state: "{{ state }}"
    wait: "yes"
    os_username: "{{ username }}"
    os_password: "{{ password }}"
    os_tenant_name: "{{ project }}"
    os_auth_url: "{{ endpoint }}"
    parameters: "{{ heat_params }}"
  register: output
