---
- name: "Set default res_grp_vars when not defined"
  set_fact:
    res_grp_vars:
      - name: "{{ res_def['res_name'] | default(res_def['vm_name']) }}"
        resource_group_name: "{{ res_grp_name  }}"

# - name: Update Instance Tags
#   set_fact:
#     instance_tags: "{{ res_grp_vars | selectattr('resource_group_name', 'match', '^' + res_grp_name + '$') | first | combine( res_def['instance_tags'] | default({}) ) }}"

- name: "Provisioning Azure VM when not async"
  azure_rm_virtualmachine:
    client_id: "{{ auth_var['client_id'] | default(omit) }}"
    tenant: "{{ auth_var['tenant'] | default(omit) }}"
    secret: "{{ auth_var['secret'] | default(omit) }}"
    subscription_id: "{{ auth_var['subscription_id'] | default(omit) }}"
    admin_username: "{{ res_def['vm_username'] | default(omit) }}"
    admin_password: "{{ res_def['vm_password'] | default(omit) }}"
    resource_group: "{{ res_def['resource_group'] | default(omit) }}"
    vm_size: "{{ res_def['vm_size'] | default(omit) }}"
    name: "{{ res_def['vm_name'] | default(omit) }}"
    image: "{{ res_def['image'] | default(omit) }}"
    #leave the code below here for now, implement later
    # image: 
    #   offer: CentOS
    #   publisher: OpenLogic
    #   sku: '7.1'
    #   version: latest
  register: res_def_output
  when: not _async
  # no_log: "{{ not debug_mode }}"

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_azure_vm: "{{ topology_outputs_azure_vm + [res_def_output] }}"
  when: res_def_output['changed'] == true and not _async

- name: "Async:: Provisioning Azure VM"
  azure_rm_virtualmachine:
    client_id: "{{ auth_var['client_id'] | default(omit) }}"
    tenant: "{{ auth_var['tenant'] | default(omit) }}"
    secret: "{{ auth_var['secret'] | default(omit) }}"
    subscription_id: "{{ auth_var['subscription_id'] | default(omit) }}"
    admin_username: "{{ res_def['vm_username'] | default(omit) }}"
    admin_password: "{{ res_def['vm_password'] | default(omit) }}"
    resource_group: "{{ res_def['resource_group'] | default(omit) }}"
    vm_size: "{{ res_def['vm_size'] | default(omit) }}"
    name: "{{ res_def['vm_name'] | default(omit) }}"
    image: "{{ res_def['image'] | default(omit) }}"
    #leave the code below here for now, implement later
    # image: 
    #   offer: CentOS
    #   publisher: OpenLogic
    #   sku: '7.1'
    #   version: latest
  async: "{{ async_timeout }}"
  poll: 0
  register: res_def_output
  when: _async
  no_log: "{{ not debug_mode }}"

- name: "Async:: Append outputitem to topology_outputs"
  set_fact:
    async_outputs_azure_vm: "{{ async_outputs_azure_vm + [res_def_output] }}"
  when: _async


- name: "Add type to resource"
  set_fact:
    topology_outputs_azure_vm: "{{ topology_outputs_azure_vm | add_res_type( 'azure_vm') }}"


- name: "Async:: Add type to resource"
  set_fact:
    async_outputs_azure_vm: "{{ async_outputs_azure_vm | add_res_type( 'azure_vm') }}"
  when: _async
