- name: "Debug:: checking heat parameters "
  debug:
    msg: "{{ res_grp_vars | selectattr('resource_group_name', 'equalto', res_grp_name ) | first }}"

- name: "Set Heat parameters for template"
  set_fact:
    heat_params : "{{ res_grp_vars | selectattr('resource_group_name', 'equalto', res_grp_name ) | first }}"

- name: "Set Heat parameters for template"
  set_fact:
    heat_params : "{{ heat_params['heat_params'] }}"

- name: "provision/deprovision os_heat stack"
  os_stack:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    auth:
      auth_url: "{{ endpoint }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project }}"
    state: "{{ state }}"
    template: "{{ res_def['template_path'] }}"
    parameters: "{{ heat_params }}"
  register: res_def_output
  when: not async

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_os_heat: "{{ topology_outputs_os_heat + [ res_def_output.output ] }}"
  when: not async

- name: "provision/deprovision os_heat stack"
  os_stack:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    auth:
      auth_url: "{{ endpoint }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project }}"
    state: "{{ state }}"
    template: "{{ res_def['template_path'] }}"
    parameters: "{{ heat_params }}"
  async: "{{ async_timeout }}"
  poll: 0
  register: res_def_output
  when: async

# following tasks saves the async job details
- name: "Async:: save the job id"
  set_fact:
    topology_outputs_os_heat: "{{ topology_outputs_os_heat + [ res_def_output ] }}"
  when: async
