---
- hosts: '{{ hosts | default("all") }}'
  become: '{{ become | default("no") }}'
  become_user: '{{ become_user | default("root") }}'
  remote_user: '{{ remote_user | default("root") }}'
  gather_facts: '{{ gather_facts | default("yes") }}'
  roles:
    - { role: openstack, when: setup_openstack_workspace|bool == true }
